-- Estrutura inicial do monitoramento.
-- Execute no SQL Editor do seu Supabase de DESENVOLVIMENTO.

create table if not exists public.monitoramento (
    id bigint generated by default as identity primary key,
    data_hora timestamptz not null default now(),
    status text not null check (status in ('online', 'offline', 'degraded')),
    latencia_ms numeric(10,2),
    http_status integer,
    erro text
);

create index if not exists idx_monitoramento_data_hora
on public.monitoramento (data_hora desc);

create table if not exists public.perfis (
    id uuid primary key references auth.users(id) on delete cascade,
    nome text,
    role text not null default 'visualizador'
        check (role in ('admin', 'operador', 'visualizador')),
    ativo boolean not null default true,
    criado_em timestamptz not null default now()
);

create table if not exists public.sessoes (
    id bigint generated by default as identity primary key,
    usuario_id uuid references auth.users(id) on delete set null,
    login_em timestamptz not null default now(),
    logout_em timestamptz,
    ultimo_acesso timestamptz not null default now(),
    ip text
);

create table if not exists public.logs (
    id bigint generated by default as identity primary key,
    usuario_id uuid references auth.users(id) on delete set null,
    acao text not null,
    detalhes jsonb,
    data_hora timestamptz not null default now()
);

-- RLS será refinada na fase de autenticação.
alter table public.monitoramento enable row level security;
alter table public.perfis enable row level security;
alter table public.sessoes enable row level security;
alter table public.logs enable row level security;
